# Generated by Django 3.2.8 on 2021-10-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
