# Generated by Django 3.2.8 on 2021-10-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
