# Generated by Django 3.2.8 on 2021-10-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clínica', 'verbose_name_plural': 'Clínicas'},
        ),
    ]
