# Generated by Django 3.2.8 on 2021-10-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ong',
            old_name='telefone',
            new_name='telephone',
        ),
    ]
