# Generated by Django 3.2.8 on 2021-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_rename_telefone_ong_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='complement',
            field=models.CharField(blank=True, max_length=250, verbose_name='Complemento'),
        ),
    ]
