# Generated by Django 3.2.8 on 2021-10-18 00:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_alter_ong_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
