# Generated by Django 3.2.8 on 2021-10-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('pet', '0002_pet_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Altura do animal de estimação (cm)', verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.login'),
        ),
    ]
